server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/customer
    username: root
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true